- GlowGrow-kafka/build.gradle
- GlowGrow-kafka/src/main/java/com/tk/gg/kafka/config/KafkaConsumerConfig.java
- GlowGrow-kafka/src/main/java/com/tk/gg/kafka/config/KafkaProducerConfig.java
- GlowGrow-kafka/src/main/resources/application.properties
- GlowGrow-kafka/src/main/resources/application.yml
- docker/docker-compose-kafka.yml
#4 
- kafka config 세팅(Producer, Consumer)
- docker-compose-kafka 세팅
>
> Feat : Kafka 모듈 세팅

- GlowGrow-common/src/main/java/com/tk/gg/common/enums/Gender.java
- GlowGrow-common/src/main/java/com/tk/gg/common/enums/UserRole.java
- GlowGrow-common/src/main/java/com/tk/gg/common/response/ApiUtils.java
- GlowGrow-common/src/main/java/com/tk/gg/common/response/GlobalExceptionResponse.java
- GlowGrow-common/src/main/java/com/tk/gg/common/response/GlobalResponse.java
- GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlobalExceptionHandler.java
- GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
- GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowException.java
issues : #24
#24
> 공통 응답을 개발하였습니다.
>
> 
> [FEAT] 공통 응답 개발

- GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
- GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
- post/build.gradle
- post/src/main/java/com/tk/gg/post/PostApplication.java
- post/src/main/java/com/tk/gg/post/application/dto/PostRequestDto.java
- post/src/main/java/com/tk/gg/post/application/dto/PostResponseDto.java
- post/src/main/java/com/tk/gg/post/application/service/PostService.java
- post/src/main/java/com/tk/gg/post/domain/model/Post.java
- post/src/main/java/com/tk/gg/post/domain/repository/PostRepository.java
- post/src/main/java/com/tk/gg/post/presentation/controller/PostController.java
- post/src/main/resources/application.yml
#18 , #26 
- Post 게시글 스켈레톤 CRUD 기능 구현
- 공통 응답 메시지 파일 추가
>
> [FEAT] Post 게시글 Skeleton CRUD 기능 구현

- reservation/src/main/java/com/tk/gg/reservation/ReservationApplication.java
- reservation/src/main/java/com/tk/gg/reservation/application/dto/CreateTimeSlotRequestDto.java
- reservation/src/main/java/com/tk/gg/reservation/application/dto/TimeSlotDto.java
- reservation/src/main/java/com/tk/gg/reservation/application/dto/UpdateTimeSlotRequestDto.java
- reservation/src/main/java/com/tk/gg/reservation/application/service/TimeSlotService.java
- reservation/src/main/java/com/tk/gg/reservation/domain/model/TimeSlot.java
- reservation/src/main/java/com/tk/gg/reservation/domain/repository/TimeSlotRepositoryCustom.java
- reservation/src/main/java/com/tk/gg/reservation/domain/service/TimeSlotDomainService.java
- reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/TimeSlotRepository.java
- reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/TimeSlotRepositoryImpl.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/controller/TimeSlotController.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/request/CreateTimeSlotRequest.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/request/UpdateTimeSlotRequest.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/response/TimeSlotResponse.java
- Fixed about #11
**Fix**
- 커스텀 ReposiotryImpl 잘못된 네이밍 수정
- API url 수정 ( **s** 빠져서 수정 )
**Refactor**
- 페이징 관련 직렬화 옵션 설정 
- 날짜 필드타입 LocalDate 로 수정
- application component-scan 범위 지정
> [Fix] TimeSlot 관련 코드 수정

- post/src/main/java/com/tk/gg/post/application/dto/LikeResponseDto.java
- post/src/main/java/com/tk/gg/post/application/service/LikeService.java
- Fixed about <#39>
Fix
- 게시물 좋아요 처리시 응답 Dto 수정
- LikeService 리팩토링
>
> [FIX] Like 좋아요수 응답Dto 수정 및 리팩토링

- reservation/src/main/java/com/tk/gg/reservation/application/dto/CreateReviewDto.java
- reservation/src/main/java/com/tk/gg/reservation/application/dto/ReviewDto.java
- reservation/src/main/java/com/tk/gg/reservation/application/dto/ReviewWithReservationDto.java
- reservation/src/main/java/com/tk/gg/reservation/application/dto/UpdateReviewDto.java
- reservation/src/main/java/com/tk/gg/reservation/application/service/ReviewService.java
- reservation/src/main/java/com/tk/gg/reservation/domain/model/Review.java
- reservation/src/main/java/com/tk/gg/reservation/domain/repository/ReviewRepositoryCustom.java
- reservation/src/main/java/com/tk/gg/reservation/domain/service/ReviewDomainService.java
- reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReviewRepository.java
- reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReviewRepositoryImpl.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/controller/ReviewController.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/request/CreateReviewRequest.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/request/ReviewSearchCondition.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/request/UpdateReviewRequest.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/response/ReviewResponse.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/response/ReviewWithReservationResponse.java
This PR closes #14 
- 리뷰 엔티티 작성
- 리뷰 CRUD 작성
TODO
- 리뷰 시 예외 처리 ( 유저 Role 에 따른 검증 등 )
- common 에 공통 enum 추가
> [FEAT] 리뷰 및 평점 기본 CRUD 구현

- GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
- GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
- reservation/src/main/java/com/tk/gg/reservation/application/service/ReservationService.java
- reservation/src/main/java/com/tk/gg/reservation/application/service/ReviewService.java
- reservation/src/main/java/com/tk/gg/reservation/domain/service/ReservationDomainService.java
- reservation/src/main/java/com/tk/gg/reservation/domain/service/ReviewDomainService.java
- reservation/src/main/java/com/tk/gg/reservation/domain/service/TimeSlotDomainService.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/controller/ReservationController.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/controller/ReviewController.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/controller/TimeSlotController.java
- reservation/src/test/java/com/tk/gg/reservation/application/service/ReviewServiceTest.java
- This PR closes #44 
- common 모듈에 서비스의 api 반환 메시지와, 에러 메시지를 enum 으로 추가 및 코드에 반영
-  리뷰 생성 시 예약 status 에 따른 생성 제한 서비스테스트 코드 작성
> [FEAT] 예약 서비스 모듈 반환 메시지, 에러 enum 정의, 리뷰 생성 시 서비스 테스트 작성

- GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
- GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
- post/build.gradle
- post/src/main/java/com/tk/gg/post/application/dto/MultiMediaSearchDto.java
- post/src/main/java/com/tk/gg/post/application/dto/MultimediaDto.java
- post/src/main/java/com/tk/gg/post/application/service/MultimediaService.java
- post/src/main/java/com/tk/gg/post/application/service/UploadService.java
- post/src/main/java/com/tk/gg/post/domain/model/Multimedia.java
- post/src/main/java/com/tk/gg/post/domain/repository/MultimediaRepository.java
- post/src/main/java/com/tk/gg/post/domain/repository/MultimediaRepositoryCustom.java
- post/src/main/java/com/tk/gg/post/domain/repository/MultimediaRepositoryCustomImpl.java
- post/src/main/java/com/tk/gg/post/domain/service/MultimediaDomainService.java
- post/src/main/java/com/tk/gg/post/domain/type/FileType.java
- post/src/main/java/com/tk/gg/post/infrastructure/S3UploadService.java
- post/src/main/java/com/tk/gg/post/lib/FileUtil.java
- post/src/main/java/com/tk/gg/post/presentation/controller/MultimediaController.java
- #55
- 게시판 멀티미디어 기능 구현
- S3 파일 업로드, 복사, 삭제
- 파일 업로드 크기 제한
- QureyDsl을 사용한 검색 기능 구현
>
> [FEAT] 게시판_멀티미디어 기능 구현

- post/src/main/java/com/tk/gg/post/application/dto/PostResponseDto.java
- post/src/main/java/com/tk/gg/post/application/service/CommentService.java
- post/src/main/java/com/tk/gg/post/application/service/LikeService.java
- post/src/main/java/com/tk/gg/post/application/service/PostService.java
- post/src/main/java/com/tk/gg/post/domain/model/Post.java
- post/src/main/java/com/tk/gg/post/domain/service/CommentDomainService.java
- post/src/main/java/com/tk/gg/post/domain/service/LikeDomainService.java
- post/src/main/java/com/tk/gg/post/domain/service/PostDomainService.java
- #51 
- DDD를 위한 도메인 서비스와 애플리케이션 서비스를 분리했습니다.
- 게시물 조회시 해당 게시물에 대한 멀티미디어 파일 메타데이터를 추가했습니다.
>
> [Fix] Post, Like, Comment DDD 서비스 분리

- reservation/build.gradle
- reservation/src/main/java/com/tk/gg/reservation/ReservationApplication.java
- reservation/src/main/java/com/tk/gg/reservation/application/client/UserService.java
- reservation/src/main/java/com/tk/gg/reservation/application/client/UserServiceImpl.java
- reservation/src/main/java/com/tk/gg/reservation/application/service/TimeSlotService.java
- reservation/src/main/java/com/tk/gg/reservation/domain/service/TimeSlotDomainService.java
- reservation/src/main/java/com/tk/gg/reservation/infrastructure/client/UserClient.java
- reservation/src/main/java/com/tk/gg/reservation/infrastructure/config/ComponentScanConfig.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/controller/TimeSlotController.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/request/UpdateTimeSlotRequest.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/response/TimeSlotResponse.java
- reservation/src/test/java/com/tk/gg/reservation/presentation/controller/TimeSlotControllerTest.java
#59 
Feat
- Security 모듈 의존성 추가
- TimeSlot 로직에 User 정보를 통해 로직 권한 검증
- TimeSlot 컨트롤러 단위 테스트 작성 (WebMvcTest)
Fix
- TimeSlot 요청 및 응답에서  LocalDate 와 String 끼리 변환 오류 수정
> [FEAT] 예약타임슬롯 security 적용, 유저 검증, 컨트롤러 단위 테스트 작성

- GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
- GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
- promotion/build.gradle
- promotion/src/main/java/com/tk/gg/promotion/application/dto/CouponCreateRequestDto.java
- promotion/src/main/java/com/tk/gg/promotion/application/dto/CouponIssueRequestDto.java
- promotion/src/main/java/com/tk/gg/promotion/application/scheduler/CouponStockSyncScheduler.java
- promotion/src/main/java/com/tk/gg/promotion/domain/Coupon.java
- promotion/src/main/java/com/tk/gg/promotion/domain/service/CouponDomainService.java
- promotion/src/main/java/com/tk/gg/promotion/infrastructure/repository/CouponRepository.java
- promotion/src/main/java/com/tk/gg/promotion/infrastructure/repository/CouponUserRepository.java
- promotion/src/main/java/com/tk/gg/promotion/infrastructure/repository/PromotionRepository.java
- promotion/src/main/java/com/tk/gg/promotion/infrastructure/repository/RedisRepository.java
- promotion/src/test/java/com/tk/gg/promotion/CouponIssuanceTest.java
> - #60
> - 대규모 트래픽이 발생하는 쿠폰 발급에 동시성 문제를 해결하기 위해 Redis를 도입하였습니다.
> - Redis 명령어들을 원자적으로 처리하기 위해 Lua 스크립트로 작성하였습니다.
> - 스케줄러로 매일 자정 Redis 쿠폰 재고 수량과 RDBMS 동기화 처리하였습니다.
>- 쿠폰 발급에 대해 동시성 문제를 테스트하기 위해 테스트 코드를 작성하였습니다.
>
> [FEAT] 쿠폰 발급 동시성 문제 해결

- GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
- GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
- reservation/src/main/java/com/tk/gg/reservation/application/dto/CreateReportDto.java
- reservation/src/main/java/com/tk/gg/reservation/application/dto/ReportDto.java
- reservation/src/main/java/com/tk/gg/reservation/application/service/ReportService.java
- reservation/src/main/java/com/tk/gg/reservation/domain/model/Report.java
- reservation/src/main/java/com/tk/gg/reservation/domain/service/ReportDomainService.java
- reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReportRepository.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/controller/ReportController.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/request/CreateReportRequest.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/response/ReportResponse.java
- This PR closes #15 
- 신고 엔티티 작성
- 유저 권한에 따른 제한
- 신고 생성, 단건 조회, 삭제
- 유저와 관련된 신고 목록 조회
Docs
- API 명세서 수정
- ERD 수정
> [FEAT] 신고 기능 개발

- GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
- post/build.gradle
- post/src/main/java/com/tk/gg/post/PostApplication.java
- post/src/main/java/com/tk/gg/post/application/client/UploadService.java
- post/src/main/java/com/tk/gg/post/application/client/UserService.java
- post/src/main/java/com/tk/gg/post/application/client/UserServiceImpl.java
- post/src/main/java/com/tk/gg/post/application/dto/PostResponseDto.java
- post/src/main/java/com/tk/gg/post/application/service/CommentService.java
- post/src/main/java/com/tk/gg/post/application/service/LikeService.java
- post/src/main/java/com/tk/gg/post/application/service/MultimediaService.java
- post/src/main/java/com/tk/gg/post/application/service/PostService.java
- post/src/main/java/com/tk/gg/post/domain/model/Comment.java
- post/src/main/java/com/tk/gg/post/domain/model/Like.java
- post/src/main/java/com/tk/gg/post/domain/model/Multimedia.java
- post/src/main/java/com/tk/gg/post/domain/model/Post.java
- post/src/main/java/com/tk/gg/post/domain/service/CommentDomainService.java
- post/src/main/java/com/tk/gg/post/domain/service/LikeDomainService.java
- post/src/main/java/com/tk/gg/post/domain/service/MultimediaDomainService.java
- post/src/main/java/com/tk/gg/post/domain/service/PostDomainService.java
- post/src/main/java/com/tk/gg/post/infrastructure/S3UploadService.java
- post/src/main/java/com/tk/gg/post/infrastructure/client/UserFeignClient.java
- post/src/main/java/com/tk/gg/post/presentation/controller/CommentController.java
- post/src/main/java/com/tk/gg/post/presentation/controller/LikeController.java
- post/src/main/java/com/tk/gg/post/presentation/controller/MultimediaController.java
- post/src/main/java/com/tk/gg/post/presentation/controller/PostController.java
- #63 
- user-service와 통신을 위한 Feign Client 추가
- Post, Comment, Multimedia 사용자 검증 추가
- 공통 예외 Enum 추가
>
> [FEAT] Post, Multimedia, Comment 사용자 검증 기능 구현

- GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
- GlowGrow-users/build.gradle
- GlowGrow-users/src/main/java/com/tk/gg/users/GlowGrowUsersApplication.java
- GlowGrow-users/src/main/java/com/tk/gg/users/application/client/ReservationClient.java
- GlowGrow-users/src/main/java/com/tk/gg/users/application/datainitializer/GradeDataInitializer.java
- GlowGrow-users/src/main/java/com/tk/gg/users/application/dto/UserDto.java
- GlowGrow-users/src/main/java/com/tk/gg/users/application/service/UserService.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/Grade.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/User.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/UserGrade.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/repository/grade/GradeRepository.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/service/GradeDomainService.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/service/UserDomainService.java
- GlowGrow-users/src/main/java/com/tk/gg/users/infra/messaging/GradeKafkaListener.java
- GlowGrow-users/src/main/java/com/tk/gg/users/presenation/UserController.java
- GlowGrow-users/src/main/java/com/tk/gg/users/presenation/request/UpdateUserInfoRequest.java
- GlowGrow-users/src/main/java/com/tk/gg/users/presenation/response/GradeResponse.java
- GlowGrow-users/src/main/java/com/tk/gg/users/presenation/response/ResultGradeDto.java
- GlowGrow-users/src/main/java/com/tk/gg/users/presenation/response/UserResponse.java
> #8 
> 사용자 정보 수정
> 등급 설정을 위한 기본 설정
>
> [FEAT] : User module

- reservation/src/main/java/com/tk/gg/reservation/application/dto/CreateReservationDto.java
- reservation/src/main/java/com/tk/gg/reservation/application/dto/ReservationDto.java
- reservation/src/main/java/com/tk/gg/reservation/application/dto/UpdateReservationDto.java
- reservation/src/main/java/com/tk/gg/reservation/domain/model/Reservation.java
- reservation/src/main/java/com/tk/gg/reservation/infrastructure/config/ComponentScanConfig.java
- reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReservationRepositoryImpl.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/request/CreateReservationRequest.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/request/UpdateReservationRequest.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/response/ReservationResponse.java
- reservation/src/test/java/com/tk/gg/reservation/application/service/ReservationServiceTest.java
- reservation/src/test/java/com/tk/gg/reservation/application/service/ReviewServiceTest.java
- reservation/src/test/java/com/tk/gg/reservation/presentation/controller/ReservationControllerTest.java
- This PR closes #91 
- 예약 엔티티 개발 시 누락된 필드를 추가
- 관련 Dto, request, response 수정
- 관련 테스트 코드 수정
> [FIX] 예약 엔티티 `price` 필드 추가 및 관련 코드 수정

- GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
- GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
- GlowGrow-users/src/main/java/com/tk/gg/users/application/client/ReservationClient.java
- GlowGrow-users/src/main/java/com/tk/gg/users/application/datainitializer/GradeDataInitializer.java
- GlowGrow-users/src/main/java/com/tk/gg/users/application/dto/CustomerGradeEvaluationDto.java
- GlowGrow-users/src/main/java/com/tk/gg/users/application/dto/GradeDto.java
- GlowGrow-users/src/main/java/com/tk/gg/users/application/dto/ProviderGradeEvaluationDto.java
- GlowGrow-users/src/main/java/com/tk/gg/users/application/dto/UserGradeDto.java
- GlowGrow-users/src/main/java/com/tk/gg/users/application/service/GradeService.java
- GlowGrow-users/src/main/java/com/tk/gg/users/application/service/ReservationService.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/Grade.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/UserGrade.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/repository/grade/GradeRepository.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/repository/grade/UserGradeRepository.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/service/GradeDomainService.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/type/UserGradeType.java
- GlowGrow-users/src/main/java/com/tk/gg/users/infra/config/SecurityConfig.java
- GlowGrow-users/src/main/java/com/tk/gg/users/infra/messaging/GradeKafkaListener.java
- GlowGrow-users/src/main/java/com/tk/gg/users/presenation/UserController.java
- GlowGrow-users/src/main/java/com/tk/gg/users/presenation/response/GradeResponse.java
- GlowGrow-users/src/main/java/com/tk/gg/users/presenation/response/UserGradeResponse.java
>
> #8 
> 카프카를 통한 회원 등급 관리를 개발하였습니다.
> 내 회원 등급 조회 API를 개발하였습니다.
>
> [FEAT] : 회원등급 관련 개발

- reservation/src/main/java/com/tk/gg/reservation/infrastructure/config/SecurityConfig.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/controller/GradeController.java
- reservation/src/test/java/com/tk/gg/reservation/presentation/controller/ReservationControllerTest.java
- reservation/src/test/java/com/tk/gg/reservation/presentation/controller/ReviewControllerTest.java
- This closes #88 
- SecurityConfig 작성 -> API path 별 권한 설정
- ReviewControllerTest 작성
> [FEAT] Reservation 모듈 path 별 권한 설정

- GlowGrow-common/src/main/java/com/tk/gg/common/kafka/alarm/KafkaNotificationDto.java
- GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
- GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
- notification/build.gradle
- notification/src/main/java/com/tk/gg/notification/NotificationApplication.java
- notification/src/main/java/com/tk/gg/notification/application/client/UserClient.java
- notification/src/main/java/com/tk/gg/notification/application/dto/NotificationDto.java
- notification/src/main/java/com/tk/gg/notification/application/service/NotificationService.java
- notification/src/main/java/com/tk/gg/notification/application/service/UserService.java
- notification/src/main/java/com/tk/gg/notification/domain/model/Notification.java
- notification/src/main/java/com/tk/gg/notification/domain/repository/NotificationRepository.java
- notification/src/main/java/com/tk/gg/notification/domain/service/NotificationDomainService.java
- notification/src/main/java/com/tk/gg/notification/infra/config/SecurityConfig.java
- notification/src/main/java/com/tk/gg/notification/infra/config/SwaggerConfig.java
- notification/src/main/java/com/tk/gg/notification/presentation/controller/NotificationController.java
- notification/src/main/java/com/tk/gg/notification/presentation/response/NotificationResponse.java
>
> #10 
> 알림 조회, 알림 읽음처리 개발하였습니다.
>
> [FEAT] : Notification module

- GlowGrow-common/build.gradle
- GlowGrow-common/src/main/java/com/tk/gg/common/s3/FileUtil.java
- GlowGrow-common/src/main/java/com/tk/gg/common/s3/S3UploadService.java
- GlowGrow-common/src/main/java/com/tk/gg/common/s3/UploadService.java
>
> this PR closes #98 
> s3를 이용할 공통사항 추출
>
> [FEAT] : s3

- GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
- payment/src/main/java/com/tk/gg/payment/application/dto/PaymentCancelDto.java
- payment/src/main/java/com/tk/gg/payment/application/service/PaymentService.java
- payment/src/main/java/com/tk/gg/payment/application/service/RefundService.java
- payment/src/main/java/com/tk/gg/payment/domain/model/Payment.java
- payment/src/main/java/com/tk/gg/payment/domain/model/Refund.java
- payment/src/main/java/com/tk/gg/payment/domain/service/RefundDomainService.java
- payment/src/main/java/com/tk/gg/payment/domain/type/PaymentStatus.java
- payment/src/main/java/com/tk/gg/payment/domain/type/RefundType.java
- payment/src/main/java/com/tk/gg/payment/infrastructure/controller/RefundController.java
- payment/src/main/java/com/tk/gg/payment/infrastructure/repository/PaymentRepository.java
- payment/src/main/java/com/tk/gg/payment/infrastructure/repository/RefundRepository.java
- payment/src/main/resources/static/paymentprepare.html
- #101 
- 결제 환불 기능 구현
- Payment 결제 상태 Enum 값을 수정했습니다.
- 결제 키 + 사용자 Id를 사용하여 결제 정보 존재 여부확인 코드를 추가했습니다.
>
> [FEAT] 결제 환불 기능 구현

- payment/src/main/java/com/tk/gg/payment/application/service/PaymentService.java
- payment/src/main/java/com/tk/gg/payment/domain/model/Payment.java
- payment/src/main/java/com/tk/gg/payment/domain/service/PaymentDomainService.java
- payment/src/main/java/com/tk/gg/payment/domain/type/PaymentStatus.java
- payment/src/main/java/com/tk/gg/payment/infrastructure/controller/PaymentController.java
- payment/src/main/java/com/tk/gg/payment/infrastructure/repository/PaymentRepository.java
- payment/src/main/resources/static/paymentprepare.html
- #103 
- 사용자 결제 취소시 리다이렉트 api 기능 구현
>
> [FEAT] 사용자 결제 취소 기능 구현

- GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
- GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
- payment/src/main/java/com/tk/gg/payment/application/dto/SettlementDto.java
- payment/src/main/java/com/tk/gg/payment/application/scheduler/SettlementScheduler.java
- payment/src/main/java/com/tk/gg/payment/application/service/SettlementService.java
- payment/src/main/java/com/tk/gg/payment/domain/model/Payment.java
- payment/src/main/java/com/tk/gg/payment/domain/model/Refund.java
- payment/src/main/java/com/tk/gg/payment/domain/model/Settlement.java
- payment/src/main/java/com/tk/gg/payment/domain/repository/SettlementRepositoryCustom.java
- payment/src/main/java/com/tk/gg/payment/domain/service/PaymentDomainService.java
- payment/src/main/java/com/tk/gg/payment/domain/service/SettlementDomainService.java
- payment/src/main/java/com/tk/gg/payment/domain/type/SettlementStatus.java
- payment/src/main/java/com/tk/gg/payment/infrastructure/repository/PaymentRepository.java
- payment/src/main/java/com/tk/gg/payment/infrastructure/repository/SettlementRepository.java
- payment/src/main/java/com/tk/gg/payment/infrastructure/repository/SettlementRepositoryImpl.java
- payment/src/main/java/com/tk/gg/payment/presentation/controller/PaymentController.java
- payment/src/main/java/com/tk/gg/payment/presentation/controller/RefundController.java
- payment/src/main/java/com/tk/gg/payment/presentation/controller/SettlementController.java
- #87 
- 정산 기능 구현 CRUD + S
- 정산 스케줄링 기초 코드 추가
>
> [FEAT] 정산 기능 구현

- GlowGrow-users/src/main/java/com/tk/gg/users/presenation/controller/ProfileController.java
> fix : controller url 변경

- GlowGrow-common/Dockerfile
- auth/Dockerfile
- chat/Dockerfile
- eureka/Dockerfile
- gateway/Dockerfile
- notification/Dockerfile
- payment/Dockerfile
- post/Dockerfile
- promotion/Dockerfile
- reservation/Dockerfile
#112 
- 각 서비스 Dockerfile 작성
- 멀티모듈이라 gradlew 빌드가 dockerfile 이 안되는 듯 해서 실행 스크립트만 작성
>
> [Feat] 각 서비스 Docker 파일

- .github/workflows/gradle.yml
- docker-compose.yml
- dockerTagAndPush.sh
#112 
- workflow 작성
- docker push 쉘 스크립트 작성
-  docer compose 파일 작성
> [FEAT] CI/CD 관련 파일 작성

- .github/workflows/gradle.yml
- GlowGrow-common/src/main/java/com/tk/gg/common/cors/WebConfig.java
- docker-compose.yml
> [FEAT] : Cicd 파일 변경

- auth/src/main/resources/application-prod.yml
- auth/src/main/resources/logback.xml
- chat/src/main/resources/application-prod.yml
- chat/src/main/resources/logback.xml
- payment/src/main/resources/application-prod.yml
- payment/src/main/resources/logback.xml
- post/src/main/resources/application-prod.yml
- post/src/main/resources/logback.xml
- promotion/src/main/resources/application-prod.yml
- promotion/src/main/resources/logback.xml
- #118
- 모니터링 시스템 구축을 위한 각 서비스 prometheus, logback 추가
>
> [FEAT] 모니터링 시스템 구축

- GlowGrow-common/build.gradle
- GlowGrow-users/src/main/resources/application-prod.yml
- GlowGrow-users/src/main/resources/application.yml
- GlowGrow-users/src/main/resources/logback.xml
- eureka/build.gradle
- eureka/src/main/resources/application-prod.yml
- eureka/src/main/resources/logback.xml
- gateway/build.gradle
- gateway/src/main/resources/application-prod.yml
- gateway/src/main/resources/logback.xml
- notification/src/main/resources/application-prod.yml
- notification/src/main/resources/logback.xml
- reservation/src/main/resources/application-prod.yml
- reservation/src/main/resources/logback.xml
issue: #118
>
> ex) #이슈번호, #이슈번호
>
> Feat: 모니터링 의존성 추가 및 yml 설정

- promotion/build.gradle
- promotion/src/main/java/com/tk/gg/promotion/application/serivce/PromotionApplicationService.java
- promotion/src/main/java/com/tk/gg/promotion/domain/service/CouponDomainService.java
- promotion/src/main/java/com/tk/gg/promotion/domain/service/PromotionDomainService.java
- promotion/src/main/java/com/tk/gg/promotion/infrastructure/config/SecurityConfig.java
- promotion/src/main/java/com/tk/gg/promotion/presentation/controller/CoponUserController.java
- promotion/src/main/java/com/tk/gg/promotion/presentation/controller/CouponController.java
- promotion/src/main/java/com/tk/gg/promotion/presentation/controller/PromotionController.java
- promotion/src/main/resources/application-local.yml
- promotion/src/main/resources/application-prod.yml
- promotion/src/main/resources/logback.xml
- promotion/src/test/java/com/tk/gg/promotion/CouponIssuanceTest.java
> - close #69 
> 프로모션 권한 체크 및 유저 검증 기능을 추가합니다.
>
> [FEAT] 프로모션 Security 추가 및 유저 연결, 검증

- GlowGrow-users/src/main/resources/logback.xml
- auth/src/main/resources/logback.xml
- docker-compose-local.yml
- docker/docker-compose-monitor.yml
- eureka/src/main/resources/logback.xml
- gateway/src/main/resources/logback.xml
- init-mongo.js
- init.sql
- notification/src/main/resources/logback.xml
> [BUG] local 환경에서 로그 안뜨는 버그 수정

- GlowGrow-common/src/main/java/com/tk/gg/common/response/GlobalExceptionResponse.java
- GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlobalExceptionHandler.java
#135 
- `GlobalExceptionHandler` 에 Request 객체에 대한 유효성 검증 에러 핸들러를 작성
- `GlobalExceptionResponse` 에 `validation` 필드 추가
- 예시
> [FEAT] 요청 객체 유효성 검증 에러 핸들러 작성

- GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/Award.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/Grade.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/PreferLocation.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/PreferPrice.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/PreferStyle.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/Profile.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/User.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/UserGrade.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/WorkExperience.java
- auth/src/main/java/com/tk/gg/auth/domain/repository/UserRepository.java
- auth/src/main/java/com/tk/gg/auth/domain/service/UserDomainService.java
- build.gradle
>
> #130 2
> 로그인, 회원가입 에러 수정
> 빌드시 초기화 경고문 수정
> 빌드시 테스트 코드 때문에 실패하는 경우 수정
>
> [FiIX] : user

- GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
- payment/src/main/java/com/tk/gg/payment/application/dto/PaymentResponseDto.java
- payment/src/main/java/com/tk/gg/payment/application/dto/SettlementDetailDto.java
- payment/src/main/java/com/tk/gg/payment/application/dto/SettlementDto.java
- payment/src/main/java/com/tk/gg/payment/application/service/SettlementService.java
- payment/src/main/java/com/tk/gg/payment/domain/model/Payment.java
- payment/src/main/java/com/tk/gg/payment/domain/model/Settlement.java
- payment/src/main/java/com/tk/gg/payment/domain/model/SettlementDetail.java
- payment/src/main/java/com/tk/gg/payment/domain/repository/PaymentRepositoryCustom.java
- payment/src/main/java/com/tk/gg/payment/domain/repository/SettlementDetailCustom.java
- payment/src/main/java/com/tk/gg/payment/domain/service/PaymentDomainService.java
- payment/src/main/java/com/tk/gg/payment/domain/service/SettlementDetailDomainService.java
- payment/src/main/java/com/tk/gg/payment/domain/service/SettlementDomainService.java
- payment/src/main/java/com/tk/gg/payment/infrastructure/repository/PaymentRepository.java
- payment/src/main/java/com/tk/gg/payment/infrastructure/repository/PaymentRepositoryImpl.java
- payment/src/main/java/com/tk/gg/payment/infrastructure/repository/SettlementDetailRepository.java
- payment/src/main/java/com/tk/gg/payment/infrastructure/repository/SettlementDetailRepositoryImpl.java
- payment/src/main/java/com/tk/gg/payment/infrastructure/repository/SettlementRepositoryImpl.java
- payment/src/main/java/com/tk/gg/payment/presentation/controller/SettlementController.java
- #141 
- 향후 추가적인 정보나 기능이 필요할 때 더 유연하게 대응할 수 있도록 결제-정산의 중간테이블인 정산 세부사항 테이블을 추가했습니다.
- 결제, 정산 리팩토링 (정산여부)
- 정산 비즈니스 로직 권한 체크 추가
>
> [FEAT] 정산 세부사항 기능 구현 및 결제, 정산 리팩토링

- GlowGrow-common/src/main/java/com/tk/gg/common/kafka/payment/PaymentForReservationEventDto.java
- GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
- reservation/src/main/java/com/tk/gg/reservation/application/dto/UpdateReservationDto.java
- reservation/src/main/java/com/tk/gg/reservation/application/service/ReportService.java
- reservation/src/main/java/com/tk/gg/reservation/application/service/ReservationService.java
- reservation/src/main/java/com/tk/gg/reservation/application/service/ReviewService.java
- reservation/src/main/java/com/tk/gg/reservation/application/service/TimeSlotService.java
- reservation/src/main/java/com/tk/gg/reservation/application/util/ReservationUserCheck.java
- reservation/src/main/java/com/tk/gg/reservation/domain/model/Reservation.java
- reservation/src/main/java/com/tk/gg/reservation/domain/service/ReservationDomainService.java
- reservation/src/main/java/com/tk/gg/reservation/domain/type/ReservationStatus.java
- reservation/src/main/java/com/tk/gg/reservation/infrastructure/messaging/GradeKafkaListener.java
- reservation/src/main/java/com/tk/gg/reservation/infrastructure/messaging/PaymentKafkaProducer.java
- reservation/src/main/resources/application-prod.yml
#136 
FEAT
- 완료된 예약에 대한결제 요청 카프카 이벤트 생성
REFACTOR
- 예약 데이터 유저 검증 메소드 분리 및 적용
- 예약 PUT 업데이트 시 dto 수정
-  status 변경은 PATCH 메소드로만 진행할 수 있도록 제외함
- 고객, 제공자 ID  등은 예약 ID 를 통해 조회하므로 제외함.
```java
@Component
@Slf4j(topic = "[Reservation-payment-producer]")
@RequiredArgsConstructor
public class PaymentKafkaProducer {
private final KafkaTemplate<String, Object> kafkaTemplate;
public void sendReservationToPaymentEvent(PaymentForReservationEventDto event) {
log.info("완료된 예약에 대해 결제 요청 이벤트 발행: {}", event);
kafkaTemplate.send("reservation-payment", event);
log.info("결제 요청 이벤트 발행 완료");
}
}
```
```java
public record PaymentForReservationEventDto(
UUID reservationId
) {
}
```
> [FEAT] 예약 모듈 - 결제 카프카 이벤트 작성, 리팩토링

- GlowGrow-redis/src/main/java/com/tk/gg/redis/config/RedisConfig.java
- GlowGrow-redis/src/main/resources/application.yml
- promotion/src/main/resources/application-local.yml
issue: #148
> close #148
> - #148 
>
> [Bug] 배포 환경, local환경 Redis 설정 문제 해결

- GlowGrow-common/src/main/java/com/tk/gg/common/kafka/payment/PaymentForReservationEventDto.java
- reservation/src/main/java/com/tk/gg/reservation/application/service/ReservationService.java
- This PR closes #151 
- 유저 ID 도 DTO 에 추가함
> Fix: 예약 모듈 결제 카프카 이벤트 DTO 수정

- GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
- reservation/build.gradle
- reservation/src/main/java/com/tk/gg/reservation/application/service/ReservationService.java
- reservation/src/main/java/com/tk/gg/reservation/application/service/ReviewNotifyScheduler.java
- reservation/src/main/java/com/tk/gg/reservation/application/service/ReviewService.java
- reservation/src/main/java/com/tk/gg/reservation/domain/model/Reservation.java
- reservation/src/main/java/com/tk/gg/reservation/domain/service/ReservationDomainService.java
- reservation/src/main/java/com/tk/gg/reservation/domain/service/ReviewDomainService.java
- reservation/src/main/java/com/tk/gg/reservation/domain/service/TimeSlotDomainService.java
- reservation/src/main/java/com/tk/gg/reservation/infrastructure/messaging/NotificationKafkaProducer.java
- reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReservationRepository.java
- reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReviewRepository.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/request/CreateReviewRequest.java
- reservation/src/main/java/com/tk/gg/reservation/presentation/request/UpdateReservationRequest.java
- reservation/src/test/java/com/tk/gg/reservation/application/service/ReviewNotifySchedulerTest.java
- reservation/src/test/java/com/tk/gg/reservation/presentation/controller/ReservationControllerTest.java
- reservation/src/test/resources/application-test.yml
#119 
- 예약 엔티티 status 필드에 인덱스 설정
- 스케줄러 작성
- 테스트코드로 시간 얼마나 나오나 측정 ( 정확하진 않은 것 같음)
TODO
- 성능 최적화 : 쿼리가 너무 느린 것 같다
> [FEAT] 완료예약 리뷰 알림 스케줄러 1차 작성

- chat/build.gradle
- chat/src/main/java/com/tk/gg/chat/ChatApplication.java
- chat/src/main/java/com/tk/gg/chat/application/dto/ChatMessageDto.java
- chat/src/main/java/com/tk/gg/chat/application/service/ChatApplicationService.java
- chat/src/main/java/com/tk/gg/chat/application/service/ChatMessageConsumer.java
- chat/src/main/java/com/tk/gg/chat/application/service/ChatMessageService.java
- chat/src/main/java/com/tk/gg/chat/domain/ChatMessage.java
- chat/src/main/java/com/tk/gg/chat/domain/ChattingPartcipant.java
- chat/src/main/java/com/tk/gg/chat/domain/ChattingRoom.java
- chat/src/main/java/com/tk/gg/chat/domain/service/ChatDomainService.java
- chat/src/main/java/com/tk/gg/chat/infrastructure/config/WebSocketConfig.java
- chat/src/main/java/com/tk/gg/chat/infrastructure/repository/ChatMessageRepository.java
- chat/src/main/java/com/tk/gg/chat/infrastructure/repository/ChattingRoomRepository.java
- chat/src/main/java/com/tk/gg/chat/presentation/ChatController.java
- chat/src/main/java/com/tk/gg/chat/presentation/ChattingRoomCreateRequsetDto.java
- chat/src/main/java/com/tk/gg/chat/presentation/ChattingRoomResponseDto.java
- chat/src/main/resources/application-local.yml
- chat/src/main/resources/application-prod.yml
- chat/src/main/resources/application.yml
- chat/src/main/resources/logback.xml
- gateway/src/main/resources/application.yml
> [FEAT] 채팅방 생성 및 메시지 전송 기능 구현

- promotion/src/main/java/com/tk/gg/promotion/infrastructure/repository/CouponUserRepository.java
- promotion/src/main/java/com/tk/gg/promotion/presentation/controller/CoponUserController.java
issue: #157
> close #157 
> - #157 
>
> [FEAT] 사용자 쿠폰 사용 및 사용자 쿠폰 리스트 조회 수정

- promotion/build.gradle
- promotion/src/main/java/com/tk/gg/promotion/application/dto/CouponUserResponseDto.java
- promotion/src/main/java/com/tk/gg/promotion/application/serivce/CouponApplicationService.java
- promotion/src/main/java/com/tk/gg/promotion/domain/service/CouponDomainService.java
- promotion/src/main/java/com/tk/gg/promotion/presentation/controller/CouponController.java
- promotion/src/test/java/com/tk/gg/promotion/CouponIssuanceTest.java
> [FEAT] 쿠폰생성자 권한에 따른 쿠폰 code 생성 및 사용자 쿠폰 리스트 반환시 쿠폰 code 반환 수정

- GlowGrow-common/src/main/java/com/tk/gg/common/kafka/coupon/CouponUserResponseDto.java
issue: #159
>
> ex) #이슈번호, #이슈번호
>
> [FEAT] common 모듈 response Dto 수정

- GlowGrow-users/src/main/java/com/tk/gg/users/application/service/UserService.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/Profile.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/User.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/service/ProfileDomainService.java
- GlowGrow-users/src/main/java/com/tk/gg/users/domain/service/UserDomainService.java
- GlowGrow-users/src/main/java/com/tk/gg/users/infra/repository/profile/ProfileQueryDslRepositoryImpl.java
- GlowGrow-users/src/main/java/com/tk/gg/users/presenation/controller/ProfileController.java
- GlowGrow-users/src/main/java/com/tk/gg/users/presenation/controller/UserController.java
- auth/src/main/java/com/tk/gg/auth/domain/service/UserDomainService.java
>
> #8 
> 유저 탈퇴 구현
> 유저 검색 에러 수정
>
> [Feat, Fix] user
